# Generated by Django 4.2.2 on 2024-03-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BR', 'Burger'), ('MG', 'Maggie'), ('PST', 'Pasta'), ('BVG', 'Beverages'), ('SDH', 'Sandwitch')], max_length=3),
        ),
    ]
